### PR TITLE
Reduce thread contention, allowing 8-12% faster jackhmmer

### PR DESCRIPTION
**Pull request by Augustin-Zidek**
## Summary of effects
- jackhmmer is 8-12% faster (when allowing more threads) than previous 8 threads. 
  - E.g. saves >1 minute for a uniref50 jackhmmer run on a short query protein and can save 5 minutes on a jackhmmer against uniprotkb
- even without setting threads higher than 8, jackhmmer appears to be about 3% faster on large runs
- jackhmmer run with >8 threads no longer sees performance degradation
- system-time substantially decreases when using >8 threads

## Description of change
`pthread_cond_broadcast (&queue->workerQueueCond)`:  This condition variable signals workers that new work is available.

Unnecessary Broadcasts: The `pthread_cond_broadcast` wakes up all waiting workers, even if there's only one new work item. This can cause unnecessary context switches and contention as workers compete for the lock. A `pthread_cond_signal` is more efficient, waking up just one worker. In more extreme cases, this can cause stampeding herd phenomena.

## Performance measurements
On a 128 core machine.

### jackhmmer against swissprot
(500k sequences)

```
hyperfine -r 10 --warmup 1 "jackhmmer --cpu <<N>> /tmp/hemoglobin.fasta /dev/shm/uniprot_swissprot.fasta"
```

|N cores|walltime before|walltime after|
|:----:|:----:|:----:|
|1|10.871 s ±  0.248 s|11.052 s ±  0.169 s|
|2|7.212 s ±  0.297 s|7.286 s ±  0.308 s|
|4|6.787 s ±  0.145 s|6.988 s ±  0.226 s|
|8|6.821 s ±  0.110 s|6.771 s ±  0.133 s|
|16|7.212 s ±  0.297 s|7.286 s ±  0.308 s|
|32|6.635 s ±  0.081 s|6.253 s ±  0.069 s|
|64|6.971 s ±  0.117 s|6.196 s ±  0.078 s|
|128|7.878 s ±  0.108 s|6.332 s ±  0.191 s|

### jackhmmer against UniRef50
(65M sequences)

Used 3 reruns, no warmup because it takes so long. Notably, if we compare a run of jackhmmer without the thread-contention change vs with at `--cpu=32` on UniRef, we see a huge spike in system time:
```
without: [Usertime : 1541.411 s, System time: 256.628 s]
with:    [User time: 1448.193 s, System time: 23.326 s]
```
|N cores|walltime before|walltime after|
|:----:|:----:|:----:|
|8 |606.021 s ±  9.104 s|588.184 s ± 15.256 s|
|32|608.369 s ±  ??? s|557.582 s ±  ??? s|
|128|715.781 s ±  5.827 s|536.481 s ±  0.169 s|

### jackhmmer against TrEMBL
(250M sequences)

Used a single run instead of rerunning because it takes thousands of seconds

|N cores |walltime before|walltime after|
|:----:|:----:|:----:|
|8|2692|TBD|
|128|TBD|2509 ±  ??? s|

### CODE REVIEW

**Comment by npcarter** [comment]
Thanks for sending this, it's very interesting.  I've seen evidence before
that there was a contention problem on the worker queue, and this looks
like it will help.  A big part of what you're seeing is that HMMER is
currently limited by the time required to read and parse the sequence
database, which is why you see little benefit from using more than two
cores.  As the core count gets much higher than that, the queue of
available work is effectively always empty, and the worker threads just
stall waiting for work.

-Nick

**Comment by Augustin-Zidek** [comment]
I don't think IO contention or FASTA parsing is the reason, because:

1. We typically run jackhmmer/nhmmer programs against databases that are stored in a RAM-disk (`/dev/shm/...`), so we have very fast IO on these. 
2. If we shard the in-RAM FASTA *k*-ways on a single machine and run *k* jackhmmer/nhmmer instances against these shards in parallel, we get basically linear scaling with *k* up to a certain number (somewhere around 64-128, depending on the machine). This strongly suggests that we are not saturating IO.
3. Our C++ FASTA parser can read and parse the in-RAM db much faster even with a single thread. Of course, this is just paring the FASTA, not doing any of the heavy lifting that jackhmmer does, but it shows the theoretical lower bound on the achievable speed.
4. Our observations are consistent with PyHMMER which also scales nicely with the number of threads: https://pyhmmer.readthedocs.io/en/stable/guide/benchmarks.html

**Comment by npcarter** [comment]
Huh, those pyhmmer results are really interesting.  I haven't had a chance to look at HMMER's scaling with core count in detail, but it's the next big thing on my to-do list after my current project (porting HMMER to use the AVX and AVX-512 SIMD ISAs). I'll definitely be looking at pyhmmer to see what it's doing differently.

What I've been told is that the bottleneck in our current system is the parsing time, not the file I/O, so your scaling results when you run k jackhmmer instances make sense to me, particularly for in-RAM databases.  It's possible that your FASTA parser is much faster than ours, as I haven't looked at that part of the code.  One of the ideas we're exploring is a binary sequence format that would avoid/reduce the parsing overhead.

Is your FASTA parser available somewhere that I could take a look at it?

**Comment by Augustin-Zidek** [comment]
> Huh, those pyhmmer results are really interesting. I haven't had a chance to look at HMMER's scaling with core count in detail, but it's the next big thing on my to-do list after my current project (porting HMMER to use the AVX and AVX-512 SIMD ISAs). I'll definitely be looking at pyhmmer to see what it's doing differently.

AVX and AVX-512 sound very exciting, can't wait (and thank you!).

> Is your FASTA parser available somewhere that I could take a look at it?

Indeed, here it is: 

* https://github.com/google-deepmind/alphafold3/blob/main/src/alphafold3/parsers/cpp/fasta_iterator_lib.h
* https://github.com/google-deepmind/alphafold3/blob/main/src/alphafold3/parsers/cpp/fasta_iterator_lib.cc

But I am guessing you parser does significantly more than we do, like encoding each amino acid as a numeric value.

**Comment by npcarter** [comment]
Quick update:  I took a look at the pyhmmer results you linked to, and they're avoiding the file parsing bottleneck by caching the parsed sequence/HMM file in memory so that they only have to parse it once.  That works very well for the somewhat-unusual (at least, in terms of how we run HMMER in our lab) benchmark they're running, which is searching a 2,100-sequence database against the ~20K Pfam HMMs.  For something like that, caching the parsed database will give you big speedups.  For the case we see more commonly, where someone is searching one or a few query objects against a large database, it won't help that much, and may well fail completely by overloading the memory of your machine.

If your use case involves many searches of the same database, we have a new version of the HMMER server that's in beta and will do sharded caching of parsed databases in RAM.  It gets very good speedups out to at least 500 cores used per search, and we could really use some people to help stress-test it.  If that's of interest to you, let's talk.

**Comment by Augustin-Zidek** [comment]
Yes, one of our use-cases (alphafoldserver.com) involves searching the same db with different inputs. However, we run the searches one-by-one (as user queries arrive), rather than in bulk. However, being able to cache the parsed db in RAM would be very nice for this use-case.

Our other use-case is within AlphaFold:

* https://github.com/google-deepmind/alphafold3/blob/main/src/alphafold3/data/tools/jackhmmer.py
* https://github.com/google-deepmind/alphafold3/blob/main/src/alphafold3/data/tools/nhmmer.py
* https://github.com/google-deepmind/alphafold3/blob/main/src/alphafold3/data/pipeline.py#L30

In that case we again have the same set of fixed dbs, and it would be ideal to have as low latency as possible.

However, how do you feel about this change? Are you willing to merge it?

**Comment by npcarter** [comment]
Just got done running some tests, and this change looks good, so I'm going to accept it.

**Comment by Augustin-Zidek** [comment]
Thanks, Nick! :)

**Pull request merged**
